CapaPresentacion/Controllers/FinancieraController.cs
using System.Text;
using CapaDato.Financiera;
using CapaDato.Pedido;
using CapaDato.Persona;
using CapaDato.Util;
using CapaEntidad.Control;
using CapaEntidad.Financiera;
using CapaEntidad.General;
using CapaEntidad.Menu;
using CapaEntidad.Pedido;
using CapaEntidad.Persona;
using CapaEntidad.Util;
using CapaPresentacion.Bll;
using CapaPresentacion.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using System.Data.OleDb;
using System.Globalization;

namespace CapaPresentacion.Controllers
{
    public class FinancieraController : Controller
    {
        #region <DECLARACION DE VARIABLES>
        private Dat_Pedido datPedido = new Dat_Pedido();
        private Dat_Persona datPersona = new Dat_Persona();
        private Dat_Financiera datFinanciera = new Dat_Financiera();
        private Dat_Documento_Transaccion datDocumento_Transaccion = new Dat_Documento_Transaccion();
        private Dat_Banco datBanco = new Dat_Banco();
        private Dat_Concepto datConcepto = new Dat_Concepto();
        private Dat_Pago datPago = new Dat_Pago();
        private Dat_Estado datEstado = new Dat_Estado();
        private Dat_Util datUtil = new Dat_Util();

        private string _sessionPagsLiqs = "_SessionPagsLiqs";
        private string _sessin_customer = "_sessin_customer";
        private string _session_listCuentasContables = "_session_listCuentasContables";
        private string _session_ListCuentasContables_Excel = "_session_listCuentasContables_Excel";
        private string _session_listClienteBanco = "_session_listClienteBanco";
        private string _session_listClienteBanco_Txt = "_session_listClienteBanco_Txt";
        private string _session_ListarClientePagos = "_session_ListarClientePagos";
        private string _session_ListarVerificarPagos = "_session_ListarVerificarPagos";
        private string _session_ListarVentaSemanal = "_session_ListarVentaSemanal";
        private string _session_ListarVentaSemanal_Excel = "_session_ListarVentaSemanal_Excel";
        private string _session_listSaldosAnticipos = "_session_listSaldosAnticipos";
        private string _session_ListarValidarPagos = "_session_ListarValidarPagos";
        private string _session_ListarOpeGratuitas = "_session_ListarOpeGratuitas";
        private string _session_ListarOpeGratuitas_Excel = "_session_ListarOpeGratuitas_Excel";
        private string _session_ListarSaldoCliente = "_session_ListarSaldoCliente";
        private string _session_ListarSaldoCliente_Excel = "_session_ListarSaldoCliente_Excel";
        private string _session_ListarMovimientosPagos = "_session_ListarMovimientosPagos";
        private string _session_ListarMovimientosPagos_Excel = "_session_ListarMovimientosPagos_Excel";
        #endregion
        
        public ActionResult Index()
        {
            return View();
        }
        #region Cruces

        public ActionResult CrucePago()
        {
            


            Ent_Usuario _usuario = (Ent_Usuario)Session[Ent_Constantes.NameSessionUser];

            string actionName = this.ControllerContext.RouteData.GetRequiredString("action");
            string controllerName = this.ControllerContext.RouteData.GetRequiredString("controller");
            string return_view = actionName + "|" + controllerName;

            if (_usuario == null)
            {
                return RedirectToAction("Login", "Control", new { returnUrl = return_view });
            }
            else
            {
                #region<VALIDACION DE ROLES DE USUARIO>
                Boolean valida_rol = true;
                Basico valida_controller = new Basico();
                List<Ent_Menu_Items> menu = (List<Ent_Menu_Items>)Session[Ent_Global._session_menu_user];
                valida_rol = valida_controller.AccesoMenu(menu, this);
                #endregion
                if (valida_rol)
                {
                    Session[_sessionPagsLiqs] = null;
                    //Ent_Usuario _usuario = (Ent_Usuario)Session[Ent_Constantes.NameSessionUser];
                    Ent_Pedido_Maestro maestros = datPedido.Listar_Maestros_Pedido(_usuario.usu_id, _usuario.usu_postPago, "");
                    ViewBag.listPromotor = maestros.combo_ListPromotor;
                    ViewBag.usutipo = _usuario.usu_tip_id.ToString();
                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Control", new { returnUrl = return_view });
                }
            }
        }
        public ActionResult GET_INFO_PERSONA(string codigo)
        {
            try
            {
                Ent_Persona info = datPersona.GET_INFO_PERSONA(codigo);
                Session[_sessin_customer] = info;
                Session[_sessionPagsLiqs] = getPagsLiqs(info.Bas_id);
                
                return Json(new { estado = 0, info = info});
            }
            catch (Exception ex)
            {
                return Json(new { estado = 2, mensaje = ex.Message });
            }
        }

        public List<Ent_Pag_Liq> getPagsLiqs(string custId)
        {
            return datFinanciera.getPagsLiqs(custId);
        }        
        public ActionResult getDataPagsLiqs(Ent_jQueryDataTableParams param, bool checking = false , string checkVal = "") 
        {
            /*verificar si esta null*/
            if (Session[_sessionPagsLiqs] == null)
            {
                List<Ent_Pag_Liq> listPed = new List<Ent_Pag_Liq>();
                Session[_sessionPagsLiqs] = listPed;
            }
            if (checking)
            {
                List<Ent_Pag_Liq> list = (List<Ent_Pag_Liq>)Session[_sessionPagsLiqs];
                list.Where(w => w.dtv_transdoc_id == checkVal).Select(s => { s.checks = !s.checks; return s; }).ToList();
                Session[_sessionPagsLiqs] = list;
            }

            //Traer registros

            IQueryable<Ent_Pag_Liq> membercol = ((List<Ent_Pag_Liq>)(Session[_sessionPagsLiqs])).AsQueryable();  //lista().AsQueryable();

            //Manejador de filtros
            int totalCount = membercol.Count();
            IEnumerable<Ent_Pag_Liq> filteredMembers = membercol;


            var displayMembers = filteredMembers
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength);
            var result = from a in displayMembers
                         select new
                         {
                             a.dtv_transdoc_id     ,
                             a.dtv_concept_id     ,
                             a.cov_description   ,
                             //document_date_desc = a.document_date_desc.ToString("dd/MM/yyyy hh:mm"),
                             a.document_date_desc,
                             a.dtd_document_date  ,
                             a.debito             ,
                             a.credito            ,
                             a.val                ,
                             a.TIPO               ,
                             a.active             ,
                             a.checks             ,
                             a.von_increase       ,
                             a.Flag,
                             monto = a.val * a.von_increase
                         };
            //Se devuelven los resultados por json
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = totalCount,
                iTotalDisplayRecords = filteredMembers.Count(),
                aaData = result,
                total = membercol.Where(w => w.checks).Sum(s => s.val * s.von_increase)
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult valida_cruce()
        {
            #region<REGION DE VALIDACIONES>

            string _mensaje = "";
            int estado = 0;
            if (Session[_sessionPagsLiqs] == null)
            {
                List<Ent_Pag_Liq> listPed = new List<Ent_Pag_Liq>();
                Session[_sessionPagsLiqs] = listPed;
            }

            Ent_Persona cust = (Ent_Persona)Session[_sessin_customer];

            List<Ent_Pag_Liq> list = (List<Ent_Pag_Liq>)Session[_sessionPagsLiqs];
            list = list.Where(w => w.checks).ToList();

            int countLiqSel = list.Where(w => w.dtv_concept_id == "LIQUIDACIONES").Count();
            int countPagSel = list.Where(w => w.dtv_concept_id == "PAGOS").Count();
            DataTable dtpagos = new DataTable();
            dtpagos.Columns.Add("Doc_Tra_Id", typeof(string));

            if (list.Count == 0)
            {
                estado = 1;
                _mensaje = "No ha seleccionado ningun item.";
                return Json(new { estado = estado, mensaje = _mensaje });
            }
            if (countLiqSel > 1)
            {
                estado = 1;
                _mensaje = "No se puede realizar cruce de pagos con 2 o más Pedidos, por favor seleccione solo 1 pedido.";
                return Json(new { estado = estado, mensaje = _mensaje });
            }
            if (countLiqSel == 0)
            {
                estado = 1;
                _mensaje = "no ha seleccionado ningun pedido para cruzar el pago";
                return Json(new { estado = estado, mensaje = _mensaje });
            }
            if (countPagSel > 1)
            {
                decimal _sum_pag = 0;
                decimal _liq_val = list.Where(w => w.dtv_concept_id == "LIQUIDACIONES").Select(s => s.val).FirstOrDefault();
                Int32 _limite = 0;
                foreach (Ent_Pag_Liq item in list.OrderByDescending(o => o.val))
                {
                    if (item.dtv_concept_id == "PAGOS")
                    {
                        _sum_pag += item.val;
                        if (_sum_pag > _liq_val)

CapaPresentacion/Views/Financiera/ListarClienteBanco.cshtml
@{
    ViewBag.Title = "Exportar Clientes";
    ViewBag.SubTitle = "";
}
<style>
    .table thead {
        background-color: #5799bf;
        color: #fff;
    }

    .boton-xs-td {
        padding-top: 5px !important;
        padding-bottom: 5px !important;
    }

    .alignRight {
        text-align: right;
    }
</style>
<p class="text-primary">Esta ventana permite exportar la lista de cliente.</p>
<div class="box box-header box-primary">
    <h3 class="box-title danger" style="color:#9c9c9c;font-weight:bold">Parametro de Busqueda</h3>
    <br />
    <br />
    <div class="row">
        <div class="col-sm-4">
            <label for="fecini">Seleccione banco</label>

            <div class="form-group">
                @Html.DropDownList("ddlBanco", new SelectList(ViewBag.ListarBancos, "Codigo", "Descripcion", null), new { @class = "form-control selectpicker", @data_live_search = "false", @id = "ddlBanco", @name = "ddlBanco" })
            </div>

        </div>
    </div>
</div>
<div class="box box-body box-primary">
    <div class="row">
        <div class="col-sm-4">


            <button id="btnExportar" title="Actualizar" class="btn btn-block btn-social btn-linkedin .disabled" disabled>
                <span class="glyphicon glyphicon-download-alt"></span>Exportar los datos de los clientes
            </button>
        </div>
    </div>
</div>
@section scripts{
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $("#ddlBanco").prop("selectedIndex", -1);
            $("#ddlBanco").change(function () {
                let IdBanco = $("#ddlBanco").val();
                if (IdBanco == undefined || IdBanco == null || IdBanco == 0 || IdBanco == '') {
                    $("#btnExportar").attr('disabled', 'disabled');                    
                } else {
                    $("#btnExportar").removeAttr("disabled");
                }
            })


            $("#btnExportar").click(function () {
                let IdBanco = $("#ddlBanco").val();
                waitingDialog.show("Espere por favor...")
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("get_exporta_Listar_Cliente_Banco_Txt", "Financiera")',
                    data :{
                        IdBanco : IdBanco
                    },
                    success: function (data) {
                        data = JSON.parse(data);
                        waitingDialog.hide();
                        if (data.Success) {
                            toastr.success(data.Message);
                            window.location = '@Url.Action("listClienteBancoTxt")';
                        }
                        else {
                            toastr.error(data.Message, "Alerta");
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        waitingDialog.hide();
                        toastr.error("Error al consultar.", "Alerta");
                    }
                });
            })
        })

    </script>
}