CapaPresentacion/Controllers/FacturacionController.cs
using CapaEntidad.General;
using CapaEntidad.Util;
using CapaPresentacion.Util;
using CapaEntidad.Control;
using CapaEntidad.Facturacion;
using CapaEntidad.Logistica;
using CapaEntidad.RRHH;
using CapaDato.Logistica;
using CapaDato.Facturacion;
using CapaDato.Util;
using CapaDato.RRHH;
using CapaDato.Control;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using System.Text;
using System.Data;
using Newtonsoft.Json;
using System.Reflection;
using System.Web.Script.Serialization;

namespace CapaPresentacion.Controllers
{
    public class FacturacionController : Controller
    {
        #region <DECLARACION DE VARIABLE>
        private Dat_Facturacion datFacturacion = new Dat_Facturacion();
        private Dat_Despacho dat_despacho = new Dat_Despacho();
        private Dat_Util datUtil = new Dat_Util();
        private string _session_ListarMovimientosVentas = "_session_ListarMovimientosVentas";
        private string _session_ListarMovimientosVentasChart = "_session_ListarMovimientosVentasChart";
        private string _session_ListarMovimientosVentas_Excel = "_session_ListarMovimientosVentas_Excel";
        private string _session_ListarComisiones = "_session_ListarComisiones";
        private string _session_ListarComisiones_Excel = "_session_ListarComisiones_Excel";
        private string _session_ListarVentasResumido = "_session_ListarVentasResumido";
        private string _session_ListarVentasResumido_Excel = "_session_ListarVentasResumido_Excel";
        private string _session_ListarLiderVentas = "_session_ListarLiderVentas";
        private string _session_ListarLiderVentas_Excel = "_session_ListarLiderVentas_Excel";
        private string _session_ListarVentasTallas = "_session_ListarVentasTallas";
        private string _session_ListarVentasTallas_Excel = "_session_ListarVentasTallas_Excel";
        private string _session_ListarSalidaDespacho = "_session_ListarSalidaDespacho";
        private string _session_ListarSalidaDespacho_Excel = "_session_ListarSalidaDespacho_Excel";
        private string _session_ListarSalidaDespacho_Cabecera= "_session_ListarSalidaDespacho_Cabecera";
        private string _session_ListarSalidaDespacho_Detalle = "_session_ListarSalidaDespacho_Detalle";
        private string _session_ListarVentasSemanales = "_session_ListarVentasSemanales";
        private string _session_ListarVentasSemanales_Excel = "_session_ListarVentasSemanales_Excel";
        private string _session_ListarVentasLider = "_session_ListarVentasLider";
        private string _session_ListarVentasLider_Excel = "_session_ListarVentasLider_Excel";
        private string _session_Listar_Servicio = "_session_Listar_Servicio";
        private string _session_ListarConsulta_Premios = "_session_ListarConsulta_Premios";
        private string _session_ListarConsulta_Premios_Excel = "_session_ListarConsulta_Premios_Excel";
        private string _session_ListarComision_Lider = "_session_ListarComision_Lider";
        private string _session_ListarComision_Lider_Excel = "_session_ListarComision_Lider_Excel";
        private string _session_ListarVentasStatus = "_session_ListarVentasStatus";
        private string _session_ListarVentasStatus_Excel = "_session_ListarVentasStatus_Excel";
        private string _session_ListarVentas_PorZona = "_session_ListarVentas_PorZona";
        private string _session_ListarVentas_PorZona_Excel = "_session_ListarVentas_PorZona_Excel";
        private string _session_ListarVentas_Devolucion = "_session_ListarVentas_Devolucion";
        private string _session_ListarVentas_Devolucion_Excel = "_session_ListarVentas_Devolucion_Excel";
        #endregion

        #region <CONSULTA DE VENTAS POR CATEGORIA>
        public ActionResult Ventas_Categoria()
        {
            Ent_Usuario _usuario = (Ent_Usuario)Session[Ent_Constantes.NameSessionUser];
            string actionName = this.ControllerContext.RouteData.GetRequiredString("action");
            string controllerName = this.ControllerContext.RouteData.GetRequiredString("controller");
            string return_view = actionName + "|" + controllerName;

            if (_usuario == null)
            {
                return RedirectToAction("Login", "Control", new { returnUrl = return_view });
            }
            else
            {
                Ent_Movimientos_Ventas EntMovimientosVentas = new Ent_Movimientos_Ventas();
                ViewBag.EntMovimientosVentas = EntMovimientosVentas;
                ViewBag.ListarTipoArticulo = datFacturacion.ListarTipoArticulo();
                return View();
            }

        }
        /// <summary>
        /// 
        /// </summary>
        /// <create>Juilliand R. Damian Gomez </create>
        /// <update></update> 
        /// <param name="param"></param>
        /// <param name="isOkUpdate"></param>
        /// <param name="isOkSemanal"></param>
        /// <param name="FechaInicio"></param>
        /// <param name="FechaFin"></param>
        /// <param name="TipoArticulo"></param>
        /// <returns></returns>
        public JsonResult getLisMovimientosVentaAjax(Ent_jQueryDataTableParams param, bool isOkUpdate, bool isOkSemanal,string FechaInicio, string FechaFin, string TipoArticulo)
        {
            Ent_Movimientos_Ventas EntMovimientosVentas = new Ent_Movimientos_Ventas();
            Decimal? Ventas = 0, Podv = 0, Pventas = 0, Pventasneto = 0, Pmargen = 0, Pmargenpor = 0;
            JsonResponse objResult = new JsonResponse();
            
            if (isOkUpdate)
            {                
                EntMovimientosVentas.FechaInicio = DateTime.Parse(FechaInicio);
                EntMovimientosVentas.FechaFin = DateTime.Parse(FechaFin);
                EntMovimientosVentas.IdTipoArticulo = TipoArticulo;
                List<Ent_Movimientos_Ventas> _ListarMovimientosVentas = datFacturacion.ListarVenPorCategoria(EntMovimientosVentas).ToList();
                Session[_session_ListarMovimientosVentas] = _ListarMovimientosVentas;
                Session[_session_ListarMovimientosVentasChart] = _ListarMovimientosVentas;

            }

            /*verificar si esta null*/
            if (Session[_session_ListarMovimientosVentas] == null)
            {
                List<Ent_Movimientos_Ventas> _ListarMovimientosVentas = new List<Ent_Movimientos_Ventas>();
                Session[_session_ListarMovimientosVentas] = _ListarMovimientosVentas;
            }

            if (isOkSemanal)
            {
                List<Ent_Movimientos_Ventas> _ListarData = (List<Ent_Movimientos_Ventas>)Session[_session_ListarMovimientosVentas];
                List<Ent_Movimientos_Ventas> _ListarReturn = new List<Ent_Movimientos_Ventas>();
                 _ListarReturn = (from x in _ListarData
                                  group x by x.Mcv_Description into y
                                     select new Ent_Movimientos_Ventas
                                     {
                                         Anno = 0,
                                         Can_Week_No = 0,
                                         Mcv_Description = y.Key,
                                         Ventas = y.Sum(x => x.Ventas),
                                         Podv = y.Sum(x => x.Podv),
                                         Pventas = y.Sum(x => x.Pventas),
                                         Pventasneto = y.Sum(x => x.Pventasneto),
                                         Pmargen = y.Sum(x => x.Pmargen),
                                         Pmargenpor = y.Sum(x => x.Pmargenpor)
                                     }).Distinct().ToList();
                Session[_session_ListarMovimientosVentas] = _ListarReturn;
            }

            /*Ini Crear chart*/
            List<Ent_Movimientos_Ventas> _ListarChartData = (List<Ent_Movimientos_Ventas>)Session[_session_ListarMovimientosVentasChart];
            List<Ent_Movimientos_Ventas> _ListarChartReturn = new List<Ent_Movimientos_Ventas>();
            _ListarChartReturn = (from x in _ListarChartData
                                  group x by x.Mcv_Description into y
                             select new Ent_Movimientos_Ventas
                             {
                                 Mcv_Description = y.Key,
                                 Pventasneto = y.Sum(x => x.Pventasneto)
                             }).Distinct().ToList();

            Ent_Movimientos_Ventas_Chart_Data EntMovVentasChartData = new Ent_Movimientos_Ventas_Chart_Data();
            EntMovVentasChartData.datasets = new List<Ent_Movimientos_Ventas_Chart>()
            {
                (new Ent_Movimientos_Ventas_Chart()
                {
                    label = "",
                    backgroundColor = new string[] { "#3c8dbc", "#00c0ef", "#00a65a", "#f39c12", "#f56954", "#d2d6de", "#001F3F", "#39CCCC", "#605ca8", "#ca195a", "#009473"},//Enumerable.Repeat("#0EA5FF",_ListarChartReturn.Count).ToArray(),
                    borderWidth = "1",
                    data = _ListarChartReturn.Select(s => s.Pventasneto).ToArray()
                })
            };
            EntMovVentasChartData.labels = _ListarChartReturn.Select(s => s.Mcv_Description).ToArray();
            objResult.Data = EntMovVentasChartData;
            objResult.Success = (_ListarChartData.Count == 0 ? false : true);
            var JSONChart = JsonConvert.SerializeObject(objResult);
            /*fin Crear chart*/

            IQueryable<Ent_Movimientos_Ventas> entDocTrans = ((List<Ent_Movimientos_Ventas>)(Session[_session_ListarMovimientosVentas])).AsQueryable();
            //Manejador de filtros
            int totalCount = entDocTrans.Count();
            IEnumerable<Ent_Movimientos_Ventas> filteredMembers = entDocTrans;
            if (!string.IsNullOrEmpty(param.sSearch))
            {
                filteredMembers = entDocTrans.Where(
                        m =>

CapaPresentacion/Views/Facturacion/Ventas_Anual.cshtml
@{
    ViewBag.Title = "Estadistica de Venta Anual";
    ViewBag.SubTitle = "";
}
<style>
    .table thead {
        background-color: #5799bf;
        color: #fff;
    }

    .boton-xs-td {
        padding-top: 5px !important;
        padding-bottom: 5px !important;
    }

    .alignRight {
        text-align: right;
        vertical-align: middle;
    }

    .alignCenter {
        text-align: center;
        vertical-align: middle;
    }
    /*[style RadioBox]*/
        .control {
        font-family: arial;
        display: block;
        position: relative;
        padding-left: 30px;
        margin-bottom: 10px;
        padding-top: 3px;
        cursor: pointer;
        font-size: 12px;
    }
    .control input {
        position: absolute;
        z-index: -1;
        opacity: 0;
    }
    .control_indicator {
        position: absolute;
        top: 2px;
        left: 0;
        height: 20px;
        width: 20px;
        background: #e6e6e6;
        border: 1px solid #B1BAC1;
        border-radius: undefinedpx;
    }
    .control:hover input ~ .control_indicator,
    .control input:focus ~ .control_indicator {
        background: #cccccc;
    }

    .control input:checked ~ .control_indicator {
        background: #156aac;
    }
    .control:hover input:not([disabled]):checked ~ .control_indicator,
    .control input:checked:focus ~ .control_indicator {
        background: #0e6647d;
    }
    .control input:disabled ~ .control_indicator {
        background: #e6e6e6;
        opacity: 0.6;
        pointer-events: none;
    }
    .control_indicator:after {
        box-sizing: unset;
        content: '';
        position: absolute;
        display: none;
    }
    .control input:checked ~ .control_indicator:after {
        display: block;
    }
    .control-radio .control_indicator {
        border-radius: 50%;
    }

    .control-radio .control_indicator:after {
        left: 6px;
        top: 6px;
        height: 6px;
        width: 6px;
        border-radius: 50%;
        background: #ffffff;
        transition: background 250ms;
    }
    .control-radio input:disabled ~ .control_indicator:after {
        background: #7b7b7b;
    }
    /*[/style RadioBox]*/
</style>
<p class="text-primary">Esta consulta son las ventas neto Anual.</p>
<div class="box box-header box-primary">
    <h3 class="box-title danger" style="color:#9c9c9c;font-weight:bold">Parametro de Busqueda</h3>
    <br />
    <br />
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default p-10">
                <div class="panel-body" style="padding-top: 7px;padding-bottom: 4px;margin-bottom: 9px;">
                    <label for="dtpFechaFin" style="color: #3d566e; ">Tipo de consulta</label>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-4 ">
                            <label class="control control-radio">
                                Monto
                                <input id="rdMonto" type="radio" name="radio" />
                                <div class="control_indicator"></div>
                            </label>
                        </div>
                        <div class="col-md-4">
                            <label class="control control-radio">
                                Unidad
                                <input id="rdUnidad" type="radio" name="radio" />
                                <div class="control_indicator"></div>
                            </label>
                        </div>
                        <div class="col-md-4 ">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default p-10">
                <div class="panel-body" style="padding-top: 7px;padding-bottom: 4px;">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-6 text-left">

                            </div>
                            <div class="col-md-4">
                                <label for="">Año</label>
                                <div class="form-group">
                                    @Html.DropDownList("ddlAnio", new SelectList(ViewBag.ListarAnio, "IdAnio", "IdAnio"), new { @class = "form-control selectpicker", @data_live_search = "true", @id = "ddlAnio", @name = "ddlAnio", @style = "max-width: 100%" })
                                </div>
                            </div>
                            <div class="col-md-2 text-right" >
                                <button id="btnBuscar" type="button" title="Consultar" class="btn btn-primary" style="margin-top: 22px;">
                                    <span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Buscar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="box box-header box-primary">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default p-10">
                <div class="panel-body" style="padding-top: 7px;padding-bottom: 4px;margin-bottom: 9px;">
                    <label for="dtpFechaFin" style="color: #3d566e; "></label>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-2">
                            </div>
                            <div class="col-md-8">
                                <p class="text-center">
                                    <strong id="StrComentario">Gráfico Barras - Ventas Neta Anual 2021</strong>
                                </p>
                                <div class="chart">
                                    <canvas id="ChartBar" style="height: 310px; width:500px"></canvas>
                                </div>
                            </div>
                            <!-- /.chart-responsive -->
                            <div class="col-md-2">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var objVentaAnual = {
            Inicio: function () {
                //debugger
                /*[Inicializamos variables]*/
                $("#rdMonto").attr('checked', true);
                debugger
                var date = new Date();
                var Anio = date.getFullYear();
                $('#ddlAnio').selectpicker('val', Anio);

                this.AnioSelect = $('#ddlAnio').val();
                this.IsMonto = true;
                this.IsTxtMonto = "Neta";
                this.IsTxtunidad = "Unidad";

                this.ChartBar;
                var dataV = { Success: false, Data :{}};
                objVentaAnual.generaal.GetChartBar(dataV);
                objVentaAnual.generaal.consultar();

                /*[/Inicializamos variables]*/

                /*[buscar]*/
                $("#btnBuscar").click(function () {
                    debugger
                    objVentaAnual.AnioSelect = $('#ddlAnio').val();
                    $("#StrComentario").text("Gráfico Barras - Ventas " + (objVentaAnual.IsMonto == true ? objVentaAnual.IsTxtMonto : objVentaAnual.IsTxtunidad) + " Anual " + objVentaAnual.AnioSelect)
					objVentaAnual.generaal.consultar();
                })
                /*[buscar]*/

                /*[Radio Button]*/
                $("#rdMonto").click(function () {
                    objVentaAnual.IsMonto = true;
                });

                $("#rdUnidad").click(function () {
                    objVentaAnual.IsMonto = false;
                });
                /*[/Radio Button]*/
            },            
            generaal: {
                consultar: function () {
                    var _Ent = function () { return @Html.Raw(Json.Encode(ViewBag.Ent_VentasAnual)); }();
                    _Ent.Anio = objVentaAnual.AnioSelect;
                    _Ent.Opcion = objVentaAnual.IsMonto == true ? "0" : "1";

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("getChartVentaAnual", "Facturacion")',
                        data : {_Ent:_Ent},
                        success: function (data) {
                            data = JSON.parse(data);
                            objVentaAnual.ChartBar.destroy();
                            objVentaAnual.generaal.GetChartBar(data);
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            waitingDialog.hide();
                            toastr.error("Error al exportar excel.", "Alerta");
                        }
                    });
                },
                GetChartBar: function (_data) {
                    //debugger
                    //[Config chart]
                    objVentaAnual.ChartBar = new Chart(document.getElementById("ChartBar"),
                        {
                            type: 'bar',
                            data: _data.Data,
                            plugins: [ChartDataLabels],
                            options: {
                                //title:
                                //{
                                //    display: true,
                                //    text: "Venta Neta por Categoría"
                                //},
                                //responsive: true,
                                maintainAspectRatio: true,
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true,
                                        }
                                    }],
                                    xAxes: [{
                                        ticks: {
                                            callback: function (value) {
                                                if (value.length > 7 && 5 == 6) {
                                                    return value.substr(0, 7) + "..."; //truncate
                                                } else {
                                                    return value
                                                }
                                            }
                                        }
                                    }],
                                },
                                tooltips: {
                                    mode: 'index',
                                    intersect: false,
                                    backgroundColor: 'rgba(237, 237, 237,0.8)',
                                    bodyFontColor: 'rgba(73, 73, 73,0.8)',
                                    borderWidth: 1,
                                    borderColor: 'rgba(158, 158, 158, 1)',
                                    titleFontColor: 'rgba(73, 73, 73,0.8)',
                                    callbacks: {
                                        title: function (tooltipItems, data) {
                                            //if (informe == 6){
                                            var idx = tooltipItems[0].index;
                                            return data.labels[idx]; //do something with title
                                            //}
                                        },
                                    }
                                },
                                plugins: {
                                    datalabels: {
                                        align: 'end',
                                        anchor: 'end',
                                        //color: function (context) {
                                        //    return context.dataset.backgroundColor;
                                        //},
                                        color: "#00578A",
                                        font: {
                                            weigth: 'bold',
                                            size: 12,
                                        },
                                        textAlign: 'end'
                                    }
                                },
                                legend: {
                                    display: false,
                                }
                            }
                        });
                    //[/Config chart]
                }
            }
        };
        $(document).ready(function () {
            objVentaAnual .Inicio();
        });
    </script>
}