CapaPresentacion/Models/ArticuloViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CapaPresentacion.Models
{
    public class ArticuloViewModel
    {
        public string IdArticulo { get; set; }
        public string Cat_Principal { get; set; }
        public string SubCategoria { get; set; }
        public string Marca { get; set; }
        public string Descripcion { get; set; }
        public Decimal PrecioIgv { get; set; }
        public Decimal PrecioSinIgv { get; set; }
        public Decimal Costo { get; set; }
    }
}

CapaPresentacion/Controllers/ArticuloController.cs
using CapaDato.Articulo;
using CapaDato.Pedido;
using CapaEntidad.Articulo;
using CapaEntidad.Control;
using CapaEntidad.General;
using CapaEntidad.Pedido;
using CapaEntidad.Util;
using CapaPresentacion.Bll;
using CapaPresentacion.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;


namespace CapaPresentacion.Controllers
{
    public class ArticuloController : Controller
    {
        // GET: Articulo
        private string _session_stock_x_articulo = "_session_stock_x_articulo";
        private string _session_stock_x_articulo_filtro = "_session_stock_x_articulo_filtro";
        private string _session_pedido_sin_stock = "_session_pedido_sin_stock";
        private string _session_listaArticuloPrecios = "_session_listaArticuloPrecios";
        private string _session_Lista_articulo_Excel = "_session_Lista_articulo";

        Dat_Articulo Dat_Articulo = new Dat_Articulo();
        public ActionResult Index()
        {
            return View();
        }
        #region<Stock de un Articulo>
        public FileContentResult ListaArticuloSinStockExcel()
        {

            List<Ent_Articulo_Sin_Stock> lista = (List<Ent_Articulo_Sin_Stock>)Session[_session_pedido_sin_stock];

            if (lista == null) {
                lista = new List<Ent_Articulo_Sin_Stock>();
            } 

            string[] columns = { "pedido", "dni", "nombres", "articulo", "talla", "estado" };

            byte[] filecontent = ExcelExportHelper.ExportExcel(lista, "LISTA DE ARTICULOS SIN STOCK - CATALOGO - BATA", false, columns);
            string nom_excel = "ArtsinStk_Catalogo";
            return File(filecontent, ExcelExportHelper.ExcelContentType, nom_excel + ".xlsx");
        }
        public ActionResult get_articulo_sin_stock()
        {
            string mensaje = "";
            string estado = "0";
            List<Ent_Articulo_Sin_Stock> art_sin_stk = null;
            Dat_Articulo_Stock stk_articulo = new Dat_Articulo_Stock();
            try
            {
                art_sin_stk = stk_articulo.listar_articulo_sinstock();
                if (art_sin_stk.Count == 0)
                {
                    estado = "0";
                    mensaje = "No hay pedidos para mostrar";
                }
                else
                {
                    estado = "1";
                }

            }
            catch
            {
                
            }
            Session[_session_pedido_sin_stock] = art_sin_stk;
            return Json(new { estado = estado, mensaje = mensaje });
        }
        public ActionResult getTableArticuloSinStockAjax(Ent_jQueryDataTableParams param)
        {
            /*verificar si esta null*/
            if (Session[_session_pedido_sin_stock] == null)
            {
                List<Ent_Articulo_Sin_Stock> liststock = new List<Ent_Articulo_Sin_Stock>();
                Session[_session_pedido_sin_stock] = liststock;
            }

            //}
            //Traer registros
            IQueryable<Ent_Articulo_Sin_Stock> membercol = ((List<Ent_Articulo_Sin_Stock>)(Session[_session_pedido_sin_stock])).AsQueryable();

            //Manejador de filtros
            int totalCount = membercol.Count();

            IEnumerable<Ent_Articulo_Sin_Stock> filteredMembers = membercol;


            //Manejador de orden
            var displayMembers = filteredMembers
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength);

            var result = from a in displayMembers
                         select new
                         {
                             a.pedido,
                             a.dni,
                             a.nombres,
                             a.articulo,
                             a.talla,
                             a.estado,
                         };
            //Se devuelven los resultados por json
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = totalCount,
                iTotalDisplayRecords = filteredMembers.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult get_articulo_almacen(string alm)
        {
            string mensaje = "";
            string estado = "0";
            try
            {
                List<Ent_Articulo_Stock> listar_articulo = (List<Ent_Articulo_Stock>)Session[_session_stock_x_articulo];

                if (listar_articulo == null)
                {
                    estado = "0";
                    mensaje = "Ingrese el codigo de articulo";
                }
                else
                {
                    List<Ent_Articulo_Stock> filtrar_stk = null;
                    if (alm == "AQ")
                    {
                        filtrar_stk = listar_articulo.Where(s => s.id_almacen == alm).ToList();
                    }
                    else
                    {
                        filtrar_stk = listar_articulo.Where(s => s.id_almacen.Length>0).ToList();
                    }
                    estado = "1";
                    Session[_session_stock_x_articulo_filtro] = filtrar_stk;
                }


            }
            catch (Exception)
            {

             
            }

          
            return Json(new { estado = estado, mensaje = mensaje});
        }
        public ActionResult StockArticulo()
        {
            Ent_Usuario _usuario = (Ent_Usuario)Session[Ent_Constantes.NameSessionUser];

            string actionName = this.ControllerContext.RouteData.GetRequiredString("action");
            string controllerName = this.ControllerContext.RouteData.GetRequiredString("controller");
            string return_view = actionName + "|" + controllerName;

            if (_usuario == null)
            {
                return RedirectToAction("Login", "Control", new { returnUrl = return_view });
            }
            else
            {
                Session[_session_stock_x_articulo] = null;
                Session[_session_stock_x_articulo_filtro] = null;
                Session[_session_pedido_sin_stock] = null;
                /*04 y 06 usuarios de acceso a paneles de stock y stock de */

                ViewBag.tipo_User = _usuario.usu_tip_id;

                return View();
            }

            
        }
        public ActionResult get_articulo(string articulo)
        {
            Dat_Articulo_Stock stk_articulo = new Dat_Articulo_Stock();
            List<Ent_Articulo_Stock> listar_articulo = null;
            Ent_Articulo_Info info_articulo = null;
            string mensaje = "";
            string estado = "0";
            decimal total_precio = 0;
            decimal total_costo = 0;
            try
            {
                info_articulo = new Ent_Articulo_Info();
                listar_articulo =stk_articulo.listar_stock(articulo, ref info_articulo);

                if (listar_articulo.Count == 0)
                {
                    estado = "0";
                    mensaje = "No hay stock del articulo ingresado";
                }
                else
                {

                    total_precio = listar_articulo.Where(c => c.id_almacen == "AQ").Sum(t => t.total) * info_articulo.precio;
                    total_costo = listar_articulo.Where(c => c.id_almacen == "AQ").Sum(t => t.total) * info_articulo.costo;


                    estado = "1";
                    mensaje = "";
                }

                Session[_session_stock_x_articulo] = listar_articulo;
                Session[_session_stock_x_articulo_filtro] = listar_articulo.Where(s=>s.id_almacen=="AQ").ToList();
            }
            catch 
            {

                
            }

            return Json(new { estado = estado, mensaje = mensaje,info= info_articulo,total_precio=total_precio,total_costo=total_costo });
        }

        public ActionResult getTableStockAjax(Ent_jQueryDataTableParams param)
        {
            /*verificar si esta null*/
            if (Session[_session_stock_x_articulo_filtro] == null)
            {
                List<Ent_Articulo_Stock> liststock = new List<Ent_Articulo_Stock>();
                Session[_session_stock_x_articulo_filtro] = liststock;
            }
         
            //}
            //Traer registros
            IQueryable<Ent_Articulo_Stock> membercol = ((List<Ent_Articulo_Stock>)(Session[_session_stock_x_articulo_filtro])).AsQueryable();

            //Manejador de filtros
            int totalCount = membercol.Count();

            IEnumerable<Ent_Articulo_Stock> filteredMembers = membercol;

        
            //Manejador de orden
            var displayMembers = filteredMembers
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength);

            var result = from a in displayMembers
                         select new
                         {
                             a.id_almacen,
                             a.almacen,
                             a.total,
                             a.articulo,
                             a.list_talla,  
                             a.list_pedido_sep,                           
                         };
            //Se devuelven los resultados por json
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = totalCount,
                iTotalDisplayRecords = filteredMembers.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region<Stock por Categpria>
        public ActionResult StockCategoria()
        {
            Ent_Usuario _usuario = (Ent_Usuario)Session[Ent_Constantes.NameSessionUser];

CapaPresentacion/Views/Articulo/Articulo_View.cshtml
@{
    Layout = null;
}
<style>
    .GFG {
        border-radius: 30px;
        /*background: #ffffff;*/
        padding: 25px;
        text-align:justify;
        /*width: 300px;*/
        /*height: 280px;*/
    }

    /*img.zoom {
        /*width: 350px;
    height: 200px;*/
        /*-webkit-transition: all .2s ease-in-out;
        -moz-transition: all .2s ease-in-out;
        -o-transition: all .2s ease-in-out;
        -ms-transition: all .2s ease-in-out;
    }*/*/

    .transition {
        -webkit-transform: scale(1.8);
        -moz-transform: scale(1.8);
        -o-transform: scale(1.8);
        transform: scale(1.8);
    }

    .sidebarContent {
        background-color: silver;
        /*text-align:center;
    font-size:large;*/
        /*min-height:150px;*/
        /*margin-bottom:5px;*/
    }

    .mainContent {
        background-color: silver;
        /*text-align:center;*/
        /*font-size:large;*/
        /*min-height:310px;*/
    }
</style>

<div class="row">
    <div class="col-xs-4">

        <div class="row">
            <div class="col-xs-12">

                <div class="box-body GFG">
                    <h4>Imagen:</h4>
                    <br />
                    <br />                                  
                    <img id="imagenCatalogo" style="border-top:2px solid #ffffff;border-right:1px solid ;border-bottom:2px solid #ffffff;border-left:1px solid #ffffff;" src="~/Content/images/lupa.jpg" class="img-responsive center-block d-block mx-auto zoom rounded" width="240" height="160" />                                    
                </div>

            </div>
        </div>      
    </div>
    <div class="col-xs-8">
        <div class="box-body GFG">
            <h4>Detalles:</h4>
            <ul>
                <li style="margin-top: 10px;">
                    <label>Cod Articulo: <b></b></label> <label id="lblcodigo" style="font-size:13px"  class="label label-default"></label>
                </li>
                <li style="margin-top: 10px;">
                    <label>Nombre Articulo: </label> <label id="lblnombre" style="font-size:13px" class="label label-default"></label>
                </li>
                <li style="margin-top: 10px;">
                    <label>Marca Articulo: </label> <label id="lblmarca" style="font-size:13px" class="label label-default"></label>
                </li>
                <li style="margin-top: 10px;">
                    <label>Color : </label> <label id="lblcolor" style="font-size:13px" class="label label-default"></label>
                </li>
                <li style="margin-top: 10px;">
                    <label>Categorizacion: </label> <label id="lblcategoria" style="font-size:13px" class="label label-default"></label>
                </li>  
                
                <li style="margin-top: 10px;">
                    <label style="font-size:18px;font-weight:bold">Precio: </label> <label style="font-size:17px;font-weight:bold" id="lblprecio" class="label label-danger"></label>
                </li>        
                            
               
            </ul>

        </div>
       
    </div>
</div>
    <script>
        $(document).ready(function () {
            var dataArray = function () { return @Html.Raw(Json.Encode(ViewBag.DataArticulo)); }();
            $('#lblcodigo').html(dataArray.Art_id);
            $('#lblnombre').html(dataArray.Art_Descripcion);
            $('#lblmarca').html(dataArray.Mar_Descripcion);
            $('#lblcolor').html(dataArray.Col_Descripcion);
            $('#lblcategoria').html(dataArray.Cat_Pri_Descripcion);
            $('#lblprecio').html("S/ " + dataArray.Art_Pre_Sin_Igv.toFixed(2));

            document.getElementById('imagenCatalogo').src = dataArray.Art_Foto;
        });
    </script>

CapaPresentacion/Views/Articulo/ListaPromo.cshtml
@{
    ViewBag.Title = "Lista de Promocion";
}
<style>
    .table thead {
        background-color: #5799bf;
        color: #fff;
    }

    .boton-xs-td {
        padding-top: 5px !important;
        padding-bottom: 5px !important;
    }
</style>
<p class="text-primary">Consulta de promociones , editar y crear un nueva promocion</p>
<div class="box box-body box-default">
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("ArticuloPromocion", "Articulo",new {estado= "1"})" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>&nbsp;Crear nueva Promocion</a>
        </div>
     
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="tbpromocion" class="table table-hover table-bordered compact">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>PROMOCION</th>
                            <th>% DCTO</th>
                            <th>FEC.INI</th>
                            <th>FEC.FIN</th>
                            <th>ESTADO</th>
                            <th>PRIORIDAD</th>                            
                            <th>ACCIONES</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:"></tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>PROMOCION</th>
                            <th>% DCTO</th>
                            <th>FEC.INI</th>
                            <th>FEC.FIN</th>
                            <th>ESTADO</th>
                            <th>PRIORIDAD</th>
                            <th>ACCIONES</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#tbpromocion').DataTable({
                "language": {
                    "url": "../Scripts/DataTables/Spanish.json"
                },
                "bServerSide": true,
                "bAutoWidth": false,
                "sAjaxSource": '@Url.Action("getTablePromocionListaAjax", "Articulo")',
                "fnServerParams": function (aoData) {
                    aoData.push({ "name": "actualizar", "value": "" });
                },
                "bdestroy": true,
                "start": 0,
                "columnDefs": [{
                    "orderable": false,
                    "targets": [2, 3, 4, 5, 7],
                }],
                "order": [[ 0, "desc" ]],
                "bDeferRender": true,
                "aoColumns": [
                      { "sName": "Prom_ID", "mData": "Prom_ID" },
                      { "sName": "Prom_Des", "mData": "Prom_Des" },
                      { "sName": "Prom_Porc", "mData": "Prom_Porc" },
                      { "sName": "Prom_FecIni", "mData": "Prom_FecIni" },
                      { "sName": "Prom_FecFin", "mData": "Prom_FecFin" },
                      { "sName": "Prom_EstID", "mData": "Prom_EstID" },
                      { "sName": "Prom_Prioridad", "mData": "Prom_Prioridad" },                      
                       {
                           "render": function (data, type, full) {

                               var id = full.Prom_ID;

                               var btnEdit = '<button type="submit" title="Editar Promocion" onclick="Editar(\'' + id + '\');" class="btn btn-xs btn-default btn-tabla editar-fila"><span class="fa fa-pencil text-primary"></span></button>';

                             
                               return btnEdit;
                           }, "class": "boton-xs-td"
                       },
                ]
            });
        });

        function Editar(id) {
            window.location = "@Url.Action("ArticuloPromocion", "Articulo")" + "?estado=2&promid=" + id;
        }

    </script>



}

CapaPresentacion/Views/Articulo/ListarArticulo.cshtml
@{
    ViewBag.Title = "Lista de Articulos";
    ViewBag.SubTitle = "";
}
<style>
    .table thead {
        background-color: #5799bf;
        color: #fff;
    }

    .boton-xs-td {
        padding-top: 5px !important;
        padding-bottom: 5px !important;
    }

    .alignRight {
        text-align: right;
    }
</style>
<p class="text-primary">Esta ventana muestra los precios de los articulos.</p>

@*<button type="submit" title="Editar datos del cliente" onclick="" class="btn btn-xs btn-default btn-tabla editar-fila"><span class="fa fa-pencil text-primary"></span></button>*@

<div class="box box-body box-default">
    <div class="row">
        <div class="col-md-6">
            <button id="btnRefrescar" title="Actualizar" class="btn btn-success">
                <span class="glyphicon glyphicon-refresh"></span>&nbsp;&nbsp;Refresh
            </button>
        </div>
        <div class="col-md-6 text-right">
            <button id="btnExportar" title="Actualizar" class="btn btn-success">
                <span class="glyphicon glyphicon-export"></span>&nbsp;&nbsp;Exportar Lista
            </button>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table id="tbArticulos" class="table table-hover table-bordered compact">
                    <thead>
                        <tr>
                            <th>Categoría</th>
                            <th>Sub Categoría</th>
                            <th>Marca</th>
                            <th>Descripción</th>
                            <th>Articulo</th>
                            <th>Precio Inc(Igv)</th>
                            <th>Precio Sin(Igv)</th>
                            <th>Precio Costo</th>
                            <th>Temporada</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:"></tbody>
                    <tfoot>
                        <tr>
                            <th>Categoría</th>
                            <th>Sub Categoría</th>
                            <th>Marca</th>
                            <th>Descripción</th>
                            <th>Articulo</th>
                            <th>Precio Inc(Igv)</th>
                            <th>Precio Sin(Igv)</th>
                            <th>Temporada</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            var tipo_user=@ViewBag.usu_tip_id;
            var IsOk = false;

            var actualizar='0';

            //var tipo_user = '0';
            if (tipo_user == '04' || tipo_user == '06') {
                IsOk = true;
            }

            $("#btnRefrescar").click(function () {
                waitingDialog.show("Espere por favor...")
                actualizar='1';
                $('#tbArticulos').DataTable().ajax.reload(function () {
                    waitingDialog.hide();
                });
            })

            $("#btnExportar").click(function () {
                waitingDialog.show("Espere por favor...")
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("get_exporta_ListaArticulo_excel", "Articulo")',
                    //data: {},
                    success: function (data) {
                        data = JSON.parse(data);
                        waitingDialog.hide();
                        if (data.Success) {
                            toastr.success(data.Message);
                            window.location = '@Url.Action("ListaArticuloPrecioExcel")';
                        }
                        else {
                            toastr.error(data.Message, "Alerta");
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        waitingDialog.hide();
                        toastr.error("Error al consultar.", "Alerta");
                    }
                });
            })

            $("body").toggleClass('sidebar-collapse');

            $('#tbArticulos').DataTable({
                "language": {
                    "url": "../Scripts/DataTables/Spanish.json"
                },
                "bServerSide": true,
                "bAutoWidth": false,
                "sAjaxSource": '@Url.Action("getListArticulosAjax", "Articulo")',
                "fnServerParams": function (aoData) {
                    aoData.push({ "name": "actualizar", "value": actualizar });
                    actualizar='';
                },
                "bdestroy": true,
                "start": 0,
                "columnDefs": [{
                    "orderable": false,
                    "targets": [5, 6, 7],
                }],
                "bDeferRender": true,
                "aoColumns": [
                        { "sName": "Cat_Principal", "mData": "Cat_Principal" },
                        { "sName": "SubCategoria", "mData": "SubCategoria" },
                        { "sName": "Marca", "mData": "Marca" },
                        { "sName": "Descripcion", "mData": "Descripcion" },
                        { "sName": "IdArticulo", "mData": "IdArticulo" },
                        {
                            "sName": "PrecioIgv", "mData": "PrecioIgv",
                            "sClass": "alignRight",
                            "render": function (data, type, full, meta) {
                                return "S/" + data.toFixed(2)
                            }
                        },
                        {
                            "sName": "PrecioSinIgv", "mData": "PrecioSinIgv",
                            "sClass": "alignRight",
                            "render": function (data, type, full, meta) {
                                return "S/" + data.toFixed(2)
                            }
                        },
                        {
                            "sName": "Costo", "mData": "Costo",
                            "sClass": "alignRight",
                            "bVisible": IsOk,
                            "render": function (data, type, full, meta) {
                                return "S/" + data.toFixed(2)
                            }
                        },
                        { "sName": "Temporada", "mData": "Temporada" }
                ]
            });
        })

    </script>
}